spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/interrupt?MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
#        dialect: org.hibernate.dialect.MySQL5Dialect
        storage_engine: innodb
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  output:
    ansi:
      enabled: always

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: EMBEDDED

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug

security:
  encrypt-key: 7a3b15e8f2772c2a9f28d04996b9f35c