spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/interrupt
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true

logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
        type.descriptor.sql: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug

security:
  encrypt-key: 7a3b15e8f2772c2a9f28d04996b9f35c
  pre-salt: salt
  post-salt: salt