spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/interrupt
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true
  h2:
    console:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

logging:
  #  pattern:
  #    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
        type.descriptor.sql: trace
      springframework:
        orm:
          jpa: debug
        transaction: debug

security:
  encrypt-key: 7a3b15e8f2772c2a9f28d04996b9f35c
  id-pre-salt: id-pre-salt
  id-post-salt: id-post-salt
  pw-pre-salt: pw-pre-salt
  pw-post-salt: pw-post-salt
  name-pre-salt: name-pre-salt
  name-post-salt: name-post-salt
  email-pre-salt: email-pre-salt
  email-post-salt: email-post-salt