### 회원 아이디 중복체크
GET localhost:8080/api/v1/members/check-login-id?loginId=testtest

### 회원 가입
POST localhost:8080/api/v1/members
Content-Type: application/json

{
  "loginId":  "testLoginId",
  "password":  "qweasd123",
  "name":  "홍길동",
  "email":  "djawnstj44@naver.com",
  "emailVerifyCodeKey": "4b6ffeb0-016c-4764-aaa0-91ad7e74cbb8"
}

### 회원 정보 수정
PATCH localhost:8080/api/v1/members/testLoginId
Content-Type: application/json

{
  "password":  "qweasd123",
  "name":  "홍길동",
  "email":  "test@test.com",
  "emailVerifyCodeKey": "111111"
}

### 회원 탈퇴
DELETE localhost:8080/api/v1/members/testLoginId
Content-Type: application/json

{
  "password":  "qweasd123"
}